version: '3.9'

services:
  web:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
    env_file:
      - .env
    expose:
      - 8000
    volumes:
      - static-data:/src/app/static
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask-simple-chats
    restart: always
    ports:
      - "5432:5432"
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static-data:/src/app/static
    depends_on:
      - web
    ports:
      - "80:80"


volumes:
  db-data:
  static-data: