"""Add message model

Revision ID: 037027ecc99a
Revises: 1898f0bcaaf5
Create Date: 2021-04-25 16:38:20.822080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037027ecc99a'
down_revision = '1898f0bcaaf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('datetime_writing', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_datetime_writing'), 'messages', ['datetime_writing'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_datetime_writing'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
