"""add chat_id into chats table and into messages table like a foreign key

Revision ID: ac141622b2da
Revises: 53a9bfcfee47
Create Date: 2021-05-03 18:37:44.253773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac141622b2da'
down_revision = '53a9bfcfee47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_pkey', 'chats', type_='primary')
    op.add_column('chats', sa.Column('chat_id', sa.Integer, primary_key=True, autoincrement=True))
    op.create_primary_key('chats_pkey', 'chats', ['chat_id'])
    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['chat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'chat_id')
    op.drop_column('chats', 'chat_id')
    op.create_primary_key('chats_pkey', 'chats', ['user1_id', 'user2_id'])
    # ### end Alembic commands ###
